### ISSUE TITLE
move resource-level attributes from DatasetDefinition to ResourceDefinition

### ISSUE THREAD

**Issue by dkrako** [pymovements/pymovements#1120]
## Description of the problem

The way how resources are defined, what content they have and how they relate to the other attributes in `DatasetDefinition` is very fiddly and not designed very well. The data structure of resources is very complex (dictionary of lists of dictionaries) and undocumented.

For each attribute (e.g., `filename_format` or `column_map`) the user has to create an entry in a dictionary where the key is the content-type (e.g., `gaze` and `precomputed_events`) of the resource. Even if a `DatasetDefinition` has just a single content type, the user has to define a dictionary. This again is unnecessarily complex.

Additionally, the docstring descriptions for the attributes are completely out-of-date and describe the state before all the breaking changes introduced last summer. This is a major problem and needs to be fixed as soon as possible.

### Improving `DatasetDefinition.resources`

Instead of using a dictionary of lists of resource dictionaries, the data structure can be simplified a lot by taking advantage of the fact that the inner resources are already dictionaries.

Instead of having an outer key, that represents the content-type (e.g., `gaze` and `precomputed_event`), having the content-type available in the inner resource dictionary is much simpler:

```
current_resources = {
    'gaze': [
        {
            'resource': 'http://example.com/myarchive.zip',
        },
    ],
    'precomputed_events': [
        {
            'resource': 'http://example.com/myfile.csv',
        },
    ],
}

proposed_resources = [
    {
        'resource': 'http://example.com/myarchive.zip',
        'content': 'gaze',
    },
    {
        'resource': 'http://example.com/myfile.csv',
        'content': 'precomputed_events',
    },
]
```

### Improving dependent `DatasetDefinition` attributes

Instead of using dictionaries for all attributes, the fact that the resources are already dictionaries can be used here as well:

```
current_filename_format = {
    'gaze': 'example-gaze-filename-format`,
    'precomputed_events': 'example-events-filename-format`,
}

proposed_resources = [
    {
        'resource': 'http://example.com/myarchive.zip',
        'content': 'gaze',
        'filename_format': 'example-gaze-filename-format`,
    },
    {
        'resource': 'http://example.com/myfile.csv',
        'content': 'precomputed_events',
        'filename_format': 'example-events-filename-format`,
    },
]

proposed_filename_format = None
```

In case of multiple content types, `DatasetDefinition.filename_format` would be required to be `None`, whereas for a `DatasetDefinition` with a single resource the `DatasetDefinition.filename_format` could be used plainly without defining it in the dictionary.

This pattern could be used for all of the attributes that are currently required to be defined as a dictionary.

### implement `DatasetResources` and `DatasetResource` classes

The `DatasetDefinition.resources` can be implemented as a dedicated class instead of a list of dictionaries.

This is helpful for the `DatasetDefinition.has_resources` property, that currently needs to be awkwardly updated before each return.
Instead, the `DatasetDefinition.has_resources` property should just forward to `DatasetResources.has_resources`.

But I would say that this is of much less importance than the first two proposals, and they should be implemented first.
After that, we can discuss what benefits a dedicated class could have.

EDIT: I reconsidere: as `Gaze()` will support a `DatasetDefinition` as input, maybe it should then also support a `ResourceDefinition` or so? Otherwise this will get complicated again in the loading logic. So maybe we should first improve the resources datas structure (step 1), then implement the resource classes (step 2) before finally improving the remaining attributes (step 3).

## Minimum acceptance criteria

- [x] change `DatasetDefinition.resources` type from `dict[str, list[dict[str, Any]]` to `list[dict[str, Any]]` and move the key of the previous outer dictionary to the value of `content` in the inner dictionary
- [x] implement `ResourceDefinition` with a `from_dict()` method, and initialize in `DatasetDefinition.__post_init__()`
- [x] define dependent attributes of `DatasetDefinition` in inner dictionary of `DatasetDefinition.resources` if resources include multiple content types

## Context

- #1064 
  this implements a `DatasetDefinition.has_resources` property that would benefit greatly from a dedicated `DatasetResources` class

**Comment by SiQube** [comment]
how about:

```yaml
name: CodeComprehension

long_name: "Code Comprehension dataset"

gaze:
  has_files: false

precomputed_events:
  has_files: true
  resources:
      - resource: "https://zenodo.org/records/11123101/files/Predicting%20Code%20Comprehension%20Package.zip?download=1"
        filename: "data.zip"
        md5: "3a3c6fb96550bc2c2ddcf5d458fb12a2"
  extract: true
  filename_format: 'fix_report_P{subject_id:s}.txt'
  filename_format_schema_overrides:
      subject_id: !polars.Utf8
  custom_read_kwargs:
      separator: "\t"
      null_values: "."
      quote_char: '"'

precomputed_reading_measures:
  has_files: false
```
